# -*- coding: utf-8 -*-
"""GitHub practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJ8Eqkxu4l9oYDe01nOT7jZaOWjQOLiE
"""

# prompt: Write a function to get input from user and display it in reverse order 2 times

def reverse_input_twice():
  """Gets input from the user and displays it in reverse order twice."""

  user_input = input("Enter some text: ")
  reversed_input = user_input[::-1]

  print(f"Reversed input: {reversed_input}")
  print(f"Reversed input again: {reversed_input}")

  ## Lets add a bug

# Call the function to run the code
reverse_input_twice()

# prompt: Write a function to get number from user and print if the number in a fibonacci series

def is_fibonacci(n):
  """Checks if a number is part of the Fibonacci sequence."""
  a, b = 0, 1
  while b < n:
    a, b = b, a + b
  return b == n

def check_fibonacci_input():
  """Gets input from the user and checks if it's a Fibonacci number."""
  try:
    num = int(input("Enter a number: "))
    if is_fibonacci(num):
      print(f"{num} is a Fibonacci number.")
    else:
      print(f"{num} is not a Fibonacci number.")
  except ValueError:
    print("Invalid input. Please enter a valid integer.")


def reverse_input():
  """Gets input from the user and displays it in reverse order."""
  user_input = input("Enter something: ")
  reversed_input = user_input[::-1]
  print("Reversed input:", reversed_input)


# Call the function to check if a number is Fibonacci
check_fibonacci_input()